name: Manual Dispatch

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'The Ubuntu release to build container image for'
        required: true
        default: jammy
        type: choice
        options:
        - bionic
        - focal
        - jammy
      release_tag:
        description: Tag the container image with the release name (instead of with just a SHA hash)
        type: boolean
        required: true
        default: false
      push:
        description: Push container image to Docker Hub
        type: boolean
        required: true
        default: false

jobs:
  build:
    name: Build ${{ inputs.release_name }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Docker image metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: mkroman/ubuntu-ansible
        tags: |
          type=sha,format=long
          type=raw,value=bionic,enable=${{ (inputs.release_tag && inputs.release_name == 'bionic') && 'true' || 'false' }}
          type=raw,value=18.04,enable=${{ (inputs.release_tag && inputs.release_name == 'bionic') && 'true' || 'false' }}
          type=raw,value=focal,enable=${{ (inputs.release_tag && inputs.release_name == 'focal') && 'true' || 'false' }}
          type=raw,value=20.04,enable=${{ (inputs.release_tag && inputs.release_name == 'focal') && 'true' || 'false' }}
          type=raw,value=jammy,enable=${{ (inputs.release_tag && inputs.release_name == 'jammy') && 'true' || 'false' }}
          type=raw,value=22.04,enable=${{ (inputs.release_tag && inputs.release_name == 'jammy') && 'true' || 'false' }}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push container image
      uses: docker/build-push-action@v3
      with:
        context: .
        pull: true
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: Dockerfile.${{ inputs.release_name }}
