name: Weekly schedule

on:
  schedule:
  - cron: '0 10 * * 0'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: [bionic, focal, jammy]
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Docker image metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: mkroman/ubuntu-ansible
        tags: |
          type=sha,format=long
          type=raw,value=bionic,enable=${{ (matrix.release == 'bionic') && 'true' || 'false' }}
          type=raw,value=18.04,enable=${{ (matrix.release == 'bionic') && 'true' || 'false' }}
          type=raw,value=focal,enable=${{ (matrix.release == 'focal') && 'true' || 'false' }}
          type=raw,value=20.04,enable=${{ (matrix.release == 'focal') && 'true' || 'false' }}
          type=raw,value=jammy,enable=${{ (matrix.release == 'jammy') && 'true' || 'false' }}
          type=raw,value=22.04,enable=${{ (matrix.release == 'jammy') && 'true' || 'false' }}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push container image
      uses: docker/build-push-action@v3
      with:
        context: .
        pull: true
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: Dockerfile.${{ matrix.release }}
